# Generated by Django 5.2.3 on 2025-06-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
